intent_analysis:
  user_prompt_template: |
    你是一个专业的医学文献分析助手，擅长理解用户的医学研究需求并分析其意图。

    请分析以下用户输入，识别其核心研究需求、文献检索策略、时间范围、以及可能的限制条件。

    用户输入: {user_input}

    请分析用户的意图并以JSON格式输出结果，包含以下字段：

    1. **query**: PubMed检索词（使用布尔操作符AND、OR、NOT，使用MeSH词汇）
    2. **year_start**: 起始年份（整数，如果用户提到了年份限制）
    3. **year_end**: 结束年份（整数，如果用户提到了年份限制）  
    4. **min_if**: 最小影响因子（浮点数，如果用户提到影响因子要求）
    5. **max_if**: 最大影响因子（浮点数，如果用户提到影响因子要求）
    6. **cas_zones**: 中科院分区限制（整数列表，1-4分区，如[1,2]表示1区和2区）
    7. **jcr_quartiles**: JCR分区限制（字符串列表，如["Q1","Q2"]）
    8. **keywords**: 关键词过滤列表（从用户输入中提取的重要关键词）

    分析规则：
    - 识别疾病名称、治疗方法、药物名称等医学概念
    - 将中文医学术语转换为英文和MeSH术语
    - 自动补充相关的同义词和相关术语
    - 基于当前年份精确计算年份限制：
      - "近年来"或"最近"：当前年-2到当前年
      - "近3年"：当前年-2到当前年
      - "近5年"：当前年-4到当前年
      - "近10年"：当前年-9到当前年
      - "最近几年"：当前年-3到当前年
      - "过去5年"：当前年-4到当前年
    - 影响因子：高影响因子=5.0以上，顶级期刊=10.0以上
    - **重要分区规则：**
      - 仅当用户明确提到"中科院分区"或"CAS分区"时，才输出cas_zones
      - 仅当用户明确提到"JCR分区"或"JCR quartile"时，才输出jcr_quartiles
      - 用户仅说"高影响因子"或"顶级期刊"时，只输出min_if，不要自动添加分区限制

    示例输出格式：
    ```json
    {{
      "query": "(diabetes mellitus[MeSH Terms] OR diabetes[Title/Abstract]) AND (treatment[MeSH Terms] OR therapy[Title/Abstract])",
      "year_start": 2020,
      "year_end": 2025,
      "min_if": 5.0,
      "keywords": ["diabetes", "treatment", "therapy"]
    }}
    ```

    请对上述用户输入进行分析并输出JSON格式结果:

outline_generation:
  user_prompt_template: |
    你是一个专业的医学综述写作专家，擅长构建结构化的文献综述大纲。

    请基于以下研究主题和文献摘要，生成一个全面的医学综述大纲：

    **研究主题**: {topic}

    **相关文献摘要**:
    {literature_summary}

    请生成一个结构化的综述大纲，包含以下要素：

    ## 综述大纲

    **标题**: [建议的综述标题]

    **预计字数**: [建议的总字数范围]

    **目标读者**: [如：临床医生、研究人员、学生等]

    ## 详细大纲

    ### 一、引言 (Introduction)
    - [背景介绍要点1]
    - [背景介绍要点2]
    - [研究意义和目的]
    - [本文结构概述]

    ### 二、[主要章节1]
    - [子章节1.1]
    - [子章节1.2]
    - [子章节1.3]

    ### 三、[主要章节2]
    - [子章节2.1]
    - [子章节2.2]
    - [子章节2.3]

    ### 四、[主要章节3]
    - [子章节3.1]
    - [子章节3.2]
    - [子章节3.3]

    ### 五、[根据需要添加更多章节]

    ### 六、结论与展望 (Conclusion and Outlook)
    - [主要发现总结]
    - [研究局限性]
    - [未来研究方向]

    ## 参考文献
    - [预计引用的文献数量和类型]

    ## 特殊说明
    - [任何特殊的写作要求或注意事项]

review_generation:
  user_prompt_template: |
    你是一位资深的医学综述撰写专家。请根据以下信息撰写一篇完整、连贯的医学综述文章。

    **文章标题**: {title}

    **综述大纲**:
    {outline_content}

    **参考文献库**:
    {literature_info}

    **撰写要求**:
    1. 严格按照提供的大纲结构撰写，保持层次分明
    2. 内容必须基于提供的文献信息，不得编造事实
    3. 使用专业的医学术语和学术语言
    4. 正文每个自然段落开头使用两个全角空格（　　）缩进
    5. 在引用文献时使用中括号数字标注，如[1]、[2]等，对应上述文献编号
    6. 各章节之间保持逻辑连贯，形成完整的论述体系
    7. 段落内语言流畅自然，避免生硬的拼接感
    8. 结论部分要总结全文，提出展望
    9. 输出完整的Markdown格式文章，包含标题层级

    请直接输出完整的综述文章：

literature_filter:
  comprehensive: 请全面筛选文献，保留所有相关的研究，包括综述和原始研究
  default: 请根据以下标准筛选文献：高质量、相关性、最新性
  strict: 请严格筛选文献，只保留高质量且高度相关的研究
pubmed_search:
  comprehensive: 请进行全面的文献检索，包括{query}相关的所有研究，并按重要性排序
  default: 请搜索关于{query}的最新研究文献，重点关注过去5年的重要进展
  recent: 请搜索最近1-2年内关于{query}的最新研究进展